//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Context
{
    using Models.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class K3CloudEntities : DbContext
    {
        public K3CloudEntities()
            : base("name=K3CloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HXN_HR_EMPLOYEE> HXN_HR_EMPLOYEE { get; set; }
        public virtual DbSet<HXN_HR_EMPLOYEE_L> HXN_HR_EMPLOYEE_L { get; set; }
        public virtual DbSet<HXN_HR_ORG> HXN_HR_ORG { get; set; }
        public virtual DbSet<HXN_HR_ORG_Group> HXN_HR_ORG_Group { get; set; }
        public virtual DbSet<HXN_HR_ORG_Group_L> HXN_HR_ORG_Group_L { get; set; }
        public virtual DbSet<HXN_HR_ORG_L> HXN_HR_ORG_L { get; set; }
        public virtual DbSet<CMK_LS_Branch> CMK_LS_Branch { get; set; }
        public virtual DbSet<CMK_LS_Branch_L> CMK_LS_Branch_L { get; set; }
    
        public virtual ObjectResult<HXN_HR_Tsui_UserInfo_Result> HXN_HR_Tsui_UserInfo(string gongHao)
        {
            var gongHaoParameter = gongHao != null ?
                new ObjectParameter("GongHao", gongHao) :
                new ObjectParameter("GongHao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HXN_HR_Tsui_UserInfo_Result>("HXN_HR_Tsui_UserInfo", gongHaoParameter);
        }
    }
}
