//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class AreaMetaData
    {
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        [Required] 
        public virtual string Code
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string Parent
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Name
        {
            get;
            set;
        }
        [Required] 
        public virtual int Type
        {
            get;
            set;
        }
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
    }
}
