//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class CMK_LS_BranchMetaData
    {
        [Required] 
        public virtual int FID
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FFormId
        {
            get;
            set;
        }
    	
        [StringLength(30, ErrorMessage="最多可输入30个字符")]
        [Required] 
        public virtual string FNUMBER
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FDOCUMENTSTATUS
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FFORBIDSTATUS
        {
            get;
            set;
        }
        [Required] 
        public virtual int FMODIFIERID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCREATORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCREATEDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FMODIFYDATE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FAPPROVERID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FAPPROVEDATE
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FCITY
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FPROVINCIAL
        {
            get;
            set;
        }
        [Required] 
        public virtual int FORGID
        {
            get;
            set;
        }
    	
        [StringLength(255, ErrorMessage="最多可输入255个字符")]
        [Required] 
        public virtual string FADDR
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FOPENDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FPAYDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCHANGDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FREOPENDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCOMPOPENDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FBEGINHIREDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FENDHIREDATE
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCLOSEDATE
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FRANK
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FCountry
        {
            get;
            set;
        }
        [Required] 
        public virtual int FSTAFFNUM
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal FAREA
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal FLONGITUDE
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal FLATITUDE
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FQUDAO
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FDAQU
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FORGTYPE
        {
            get;
            set;
        }
    	
        [StringLength(36, ErrorMessage="最多可输入36个字符")]
        [Required] 
        public virtual string FSHENGQU
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        [Required] 
        public virtual string FBranchType
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCOUNTRYID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FREGIONID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCITYID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCOUNTYID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FSTREETID
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string FCODE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FPARENTORGID
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FISZNBH
        {
            get;
            set;
        }
    }
}
