//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class OpenPlatformSubscriberMetaData
    {
        [Required] 
        public virtual long Corp
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        [Required] 
        public virtual string Openid
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string PlatformType
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Nickname
        {
            get;
            set;
        }
    	
        [StringLength(200, ErrorMessage="最多可输入200个字符")]
        [Required] 
        public virtual string Headimgurl
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Name
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Alias
        {
            get;
            set;
        }
    	
        [StringLength(2, ErrorMessage="最多可输入2个字符")]
        [Required] 
        public virtual string Gender
        {
            get;
            set;
        }
    	
        [StringLength(12, ErrorMessage="最多可输入12个字符")]
        [Required] 
        public virtual string TelePhone
        {
            get;
            set;
        }
    	
        [StringLength(11, ErrorMessage="最多可输入11个字符")]
        [Required] 
        public virtual string MobilePhone
        {
            get;
            set;
        }
        [Required] 
        public virtual int Integrate
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime EnrollTime
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
