//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class OpenPlatformMOMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string PlatformType
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        [Required] 
        public virtual string ToUserName
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        [Required] 
        public virtual string FromUserName
        {
            get;
            set;
        }
        [Required] 
        public virtual long CreateTime
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        [Required] 
        public virtual string MsgType
        {
            get;
            set;
        }
        public virtual Nullable<long> MsgID
        {
            get;
            set;
        }
        public virtual string Content
        {
            get;
            set;
        }
    	
        [StringLength(200, ErrorMessage="最多可输入200个字符")]
        public virtual string PicUrl
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string MediaId
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Location_X
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Location_Y
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Scale
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Label
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Title
        {
            get;
            set;
        }
    	
        [StringLength(200, ErrorMessage="最多可输入200个字符")]
        public virtual string Description
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Url
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Format
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Recognition
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Event
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string EventKey
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Ticket
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Latitude
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Longitude
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Precision
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime ReceiveTime
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> PerformTime
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string Performer
        {
            get;
            set;
        }
    }
}
