//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class OpenPlatformMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        [Required] 
        public virtual long Corp
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string PlatformType
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Token
        {
            get;
            set;
        }
    	
        [StringLength(200, ErrorMessage="最多可输入200个字符")]
        [Required] 
        public virtual string Appid
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        [Required] 
        public virtual string AppSecret
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        [Required] 
        public virtual string Openid
        {
            get;
            set;
        }
    	
        [StringLength(44, ErrorMessage="最多可输入44个字符")]
        [Required] 
        public virtual string AesKey
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        [Required] 
        public virtual string PrivateKey
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        [Required] 
        public virtual string PublicKey
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Required] 
        public virtual long Creator
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
