//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class SysBankMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        public virtual Nullable<long> Number
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Url
        {
            get;
            set;
        }
        [Required] 
        public virtual int Type
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        public virtual string Name
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string ShortName
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string NiceName
        {
            get;
            set;
        }
        public virtual Nullable<int> Status
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        public virtual Nullable<long> Creator
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CreateTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
