//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class UserInfoMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        public virtual string GWID
        {
            get;
            set;
        }
        public virtual string SJGW
        {
            get;
            set;
        }
        public virtual string XJGW
        {
            get;
            set;
        }
        public virtual string ORGID
        {
            get;
            set;
        }
        public virtual string 姓名
        {
            get;
            set;
        }
        public virtual string 员工工号
        {
            get;
            set;
        }
        public virtual string 岗位
        {
            get;
            set;
        }
        public virtual string 所属组织
        {
            get;
            set;
        }
        public virtual string 职级
        {
            get;
            set;
        }
        public virtual string 入职日期
        {
            get;
            set;
        }
        public virtual string 公司工龄
        {
            get;
            set;
        }
        public virtual string 出生日期
        {
            get;
            set;
        }
        public virtual string 年龄
        {
            get;
            set;
        }
        public virtual string 户口所在地
        {
            get;
            set;
        }
        public virtual string 学历
        {
            get;
            set;
        }
        public virtual string 专业
        {
            get;
            set;
        }
        public virtual string 毕业院校
        {
            get;
            set;
        }
        public virtual string 联系方式
        {
            get;
            set;
        }
        public virtual string 体系模式
        {
            get;
            set;
        }
        public virtual string 一级部门
        {
            get;
            set;
        }
        public virtual string 二级部门
        {
            get;
            set;
        }
        public virtual string 三级部门
        {
            get;
            set;
        }
        public virtual string 四级部门
        {
            get;
            set;
        }
        public virtual string 五级部门
        {
            get;
            set;
        }
        public virtual string 直接上级
        {
            get;
            set;
        }
        public virtual string 直接下级人数
        {
            get;
            set;
        }
        public virtual string 直接下级经理级以上
        {
            get;
            set;
        }
        public virtual string 直接下级经理级以下
        {
            get;
            set;
        }
        public virtual string 间接下级人数
        {
            get;
            set;
        }
        public virtual string 间接下级经理级以上
        {
            get;
            set;
        }
        public virtual string 间接下级经理级以下
        {
            get;
            set;
        }
        public virtual string 间接下级绩优人员
        {
            get;
            set;
        }
        public virtual string 间接下级绩差人员
        {
            get;
            set;
        }
        public virtual string 团队总人数
        {
            get;
            set;
        }
        public virtual string 平均年龄
        {
            get;
            set;
        }
        public virtual string 平均司龄
        {
            get;
            set;
        }
        public virtual string 满编率
        {
            get;
            set;
        }
        public virtual string 团队月工资
        {
            get;
            set;
        }
        public virtual string 销售额
        {
            get;
            set;
        }
        public virtual string 男员工占比
        {
            get;
            set;
        }
        public virtual string 大专以上占比
        {
            get;
            set;
        }
        public virtual string A90后占比
        {
            get;
            set;
        }
        public virtual string 本地人员占比
        {
            get;
            set;
        }
        public virtual string 月人员流失率
        {
            get;
            set;
        }
        public virtual string 工资销额比
        {
            get;
            set;
        }
        public virtual string 人均月工资
        {
            get;
            set;
        }
        public virtual string 人均劳效
        {
            get;
            set;
        }
        public virtual string 备注
        {
            get;
            set;
        }
    }
}
