//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.AreaMetaData))]
    public partial class Area
    {
        public string Code { get; set; }
        public string Parent { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public long ID { get; set; }
    }
}
