//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.OpenPlatformMOMetaData))]
    public partial class OpenPlatformMO
    {
        public long ID { get; set; }
        public string PlatformType { get; set; }
        public string ToUserName { get; set; }
        public string FromUserName { get; set; }
        public long CreateTime { get; set; }
        public string MsgType { get; set; }
        public Nullable<long> MsgID { get; set; }
        public string Content { get; set; }
        public string PicUrl { get; set; }
        public string MediaId { get; set; }
        public Nullable<decimal> Location_X { get; set; }
        public Nullable<decimal> Location_Y { get; set; }
        public Nullable<decimal> Scale { get; set; }
        public string Label { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Format { get; set; }
        public string Recognition { get; set; }
        public string Event { get; set; }
        public string EventKey { get; set; }
        public string Ticket { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Precision { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> PerformTime { get; set; }
        public string Performer { get; set; }
    }
}
