//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.SysAreaMetaData))]
    public partial class SysArea
    {
        public string Code { get; set; }
        public string Parent { get; set; }
        public string Name { get; set; }
        public string WeatherCode { get; set; }
        public Nullable<decimal> LocationX { get; set; }
        public Nullable<decimal> LocationY { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public long Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<long> Auditor { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<long> Canceler { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
    }
}
