//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.SysLoginLogMetaData))]
    public partial class SysLoginLog
    {
        public long ID { get; set; }
        public long Operator { get; set; }
        public string Ip { get; set; }
        public string LoginAgent { get; set; }
        public bool Success { get; set; }
        public System.DateTime Time { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
    }
}
