//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.UserInfoMetaData))]
    public partial class UserInfo
    {
        public long ID { get; set; }
        public string GWID { get; set; }
        public string SJGW { get; set; }
        public string XJGW { get; set; }
        public string ORGID { get; set; }
        public string 姓名 { get; set; }
        public string 员工工号 { get; set; }
        public string 岗位 { get; set; }
        public string 所属组织 { get; set; }
        public string 职级 { get; set; }
        public string 入职日期 { get; set; }
        public string 公司工龄 { get; set; }
        public string 出生日期 { get; set; }
        public string 年龄 { get; set; }
        public string 户口所在地 { get; set; }
        public string 学历 { get; set; }
        public string 专业 { get; set; }
        public string 毕业院校 { get; set; }
        public string 联系方式 { get; set; }
        public string 体系模式 { get; set; }
        public string 一级部门 { get; set; }
        public string 二级部门 { get; set; }
        public string 三级部门 { get; set; }
        public string 四级部门 { get; set; }
        public string 五级部门 { get; set; }
        public string 直接上级 { get; set; }
        public string 直接下级人数 { get; set; }
        public string 直接下级经理级以上 { get; set; }
        public string 直接下级经理级以下 { get; set; }
        public string 间接下级人数 { get; set; }
        public string 间接下级经理级以上 { get; set; }
        public string 间接下级经理级以下 { get; set; }
        public string 间接下级绩优人员 { get; set; }
        public string 间接下级绩差人员 { get; set; }
        public string 团队总人数 { get; set; }
        public string 平均年龄 { get; set; }
        public string 平均司龄 { get; set; }
        public string 满编率 { get; set; }
        public string 团队月工资 { get; set; }
        public string 销售额 { get; set; }
        public string 男员工占比 { get; set; }
        public string 大专以上占比 { get; set; }
        public string A90后占比 { get; set; }
        public string 本地人员占比 { get; set; }
        public string 月人员流失率 { get; set; }
        public string 工资销额比 { get; set; }
        public string 人均月工资 { get; set; }
        public string 人均劳效 { get; set; }
        public string 备注 { get; set; }
    }
}
