//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class OpenPlatformMsgMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        [Required] 
        public virtual long Corp
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string PlatformType
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        [Required] 
        public virtual string MsgType
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        [Required] 
        public virtual string Title
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        [Required] 
        public virtual string Description
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        [Required] 
        public virtual string PicUrl
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Url
        {
            get;
            set;
        }
        public virtual string Content
        {
            get;
            set;
        }
    	
        [StringLength(1000, ErrorMessage="最多可输入1000个字符")]
        public virtual string Children
        {
            get;
            set;
        }
        [Required] 
        public virtual byte Sort
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Required] 
        public virtual long Creator
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
