//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace USP.Models.ViewModel
{


    public class SysCorpMetaData
    {
        [Required]
        [Display(Name = "唯一标识")]
        public virtual long ID
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "上级公司")]
        public virtual long Parent
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "公司优先级(0-9)")]
        public virtual byte Priority
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "公司名称")]
        public virtual string Name
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "公司简称")]
        public virtual string BriefName
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "证书名称")]
        public virtual string Certificate
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "证书号码")]
        public virtual string CertificateNumber
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "法人代表")]
        public virtual string Ceo
        {
            get;
            set;
        }

        [Display(Name = "邮编")]
        public virtual string Postcode
        {
            get;
            set;
        }

        [Display(Name = "传真号")]
        public virtual string Faxcode
        {
            get;
            set;
        }

        [Display(Name = "联系人")]
        public virtual string Linkman
        {
            get;
            set;
        }

        [Display(Name = "联系手机")]
        [Phone]
        public virtual string Mobile
        {
            get;
            set;
        }

        [Display(Name = "Email")]
        public virtual string Email
        {
            get;
            set;
        }

        [Display(Name = "联系QQ")]
        public virtual string Qq
        {
            get;
            set;
        }

        [Display(Name = "微信")]
        public virtual string Wechat
        {
            get;
            set;
        }

        [Display(Name = "微博")]
        public virtual string Weibo
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "虚拟积分")]
        public virtual long VirtualIntegral
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "真实积分")]
        public virtual long RealIntegral
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "付费类型")]
        public virtual long FeeType
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "预付阀值")]
        public virtual decimal PrepayValve
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "余额")]
        public virtual decimal Balance
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "冻结余额")]
        public virtual decimal FrozenBalance
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "在途余额")]
        public virtual decimal IncomingBalance
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "佣金比例")]
        public virtual decimal Commission
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "折扣比例")]
        public virtual decimal Discount
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "省份")]
        public virtual string Province
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "地区")]
        public virtual string Area
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "县")]
        public virtual string County
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "社区")]
        public virtual string Community
        {
            get;
            set;
        }

        [StringLength(100, ErrorMessage = "最多可输入100个字符")]
        [Required]
        [Display(Name = "地址")]
        public virtual string Address
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "状态")]
        public virtual long Status
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "类型")]
        public virtual long Type
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "级别")]
        public virtual long Grade
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "行业类型")]
        public virtual long Vocation
        {
            get;
            set;
        }

        [StringLength(250, ErrorMessage = "最多可输入250个字符")]
        [Display(Name = "预留")]
        public virtual string Reserve
        {
            get;
            set;
        }

        [StringLength(250, ErrorMessage = "最多可输入250个字符")]
        [Display(Name = "备注")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "创建人")]
        public virtual long Creator
        {
            get;
            set;
        }
        [Required]
        [Display(Name = "创建时间")]
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
        [Display(Name = "审核人")]
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        [Display(Name = "审核时间")]
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        [Display(Name = "注销人")]
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        [Display(Name = "注销时间")]
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "公司Logo")]
        public virtual string LogoUrl
        {
            get;
            set;
        }

        [StringLength(50, ErrorMessage = "最多可输入50个字符")]
        [Required]
        [Display(Name = "公司图标")]
        public virtual string LogoIcon
        {
            get;
            set;
        }
    }
}
