//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class SysLoginLogMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        [Required] 
        public virtual long Operator
        {
            get;
            set;
        }
    	
        [StringLength(40, ErrorMessage="最多可输入40个字符")]
        [Required] 
        public virtual string Ip
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string LoginAgent
        {
            get;
            set;
        }
        [Required] 
        public virtual bool Success
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime Time
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
    }
}
