//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class SysOperatorMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
        [Required] 
        public virtual long Corp
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string LoginName
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string RealName
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        [Required] 
        public virtual string Password
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        public virtual string Mobile
        {
            get;
            set;
        }
    	
        [StringLength(32, ErrorMessage="最多可输入32个字符")]
        public virtual string IdCard
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Email
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string WechatOpenid
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string AlipayOpenid
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Weibo
        {
            get;
            set;
        }
    	
        [StringLength(40, ErrorMessage="最多可输入40个字符")]
        [Required] 
        public virtual string AvailableIP
        {
            get;
            set;
        }
    	
        [StringLength(6, ErrorMessage="最多可输入6个字符")]
        public virtual string WeatherCode
        {
            get;
            set;
        }
        [Required] 
        public virtual long VirtualIntegral
        {
            get;
            set;
        }
        [Required] 
        public virtual long RealIntegral
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal Balance
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal FrozenBalance
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal IncomingBalance
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal Commission
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal Discount
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Province
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Area
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string County
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Community
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string Address
        {
            get;
            set;
        }
        [Required] 
        public virtual long Status
        {
            get;
            set;
        }
        [Required] 
        public virtual long Skin
        {
            get;
            set;
        }
        public virtual Nullable<long> Grade
        {
            get;
            set;
        }
        public virtual Nullable<long> Star
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        public virtual string Session
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> LoginTime
        {
            get;
            set;
        }
    	
        [StringLength(40, ErrorMessage="最多可输入40个字符")]
        public virtual string LoginIP
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string LoginAgent
        {
            get;
            set;
        }
        public virtual Nullable<long> LoginCount
        {
            get;
            set;
        }
        public virtual Nullable<long> LoginErrorCount
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FrozenStartTime
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FrozenEndTime
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="最多可输入50个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Required] 
        public virtual long Creator
        {
            get;
            set;
        }
        [Required] 
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
