//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.HXN_HR_EMPLOYEEMetaData))]
    public partial class HXN_HR_EMPLOYEE
    {
        public int FID { get; set; }
        public string FNUMBER { get; set; }
        public string FSEX { get; set; }
        public string FDOCUMENTSTATUS { get; set; }
        public string FFORBIDSTATUS { get; set; }
        public int FMODIFIERID { get; set; }
        public int FCREATORID { get; set; }
        public Nullable<System.DateTime> FCREATEDATE { get; set; }
        public Nullable<System.DateTime> FMODIFYDATE { get; set; }
        public int FCHECKERID { get; set; }
        public Nullable<System.DateTime> FCHECKDATE { get; set; }
        public int FGROUPID { get; set; }
        public Nullable<System.DateTime> FBIRTHDATE { get; set; }
        public string FCARDNUMBER { get; set; }
        public string FMARRIAGE { get; set; }
        public string FCARDADDRESS { get; set; }
        public string FADDRESS { get; set; }
        public string FHUKOUTYPE { get; set; }
        public string FPHONE { get; set; }
        public string FEMAIL { get; set; }
        public string FLIANXIREN { get; set; }
        public string FLIANXIPHONE { get; set; }
        public string FYUANXIAO { get; set; }
        public string FZHUANYE { get; set; }
        public string FXUELI { get; set; }
        public Nullable<System.DateTime> FBIYEDATE { get; set; }
        public string FYUANXIAOTYPE { get; set; }
        public string FJIAOYUTYPE { get; set; }
        public Nullable<System.DateTime> FJOINDATE { get; set; }
        public string FYINGPIN { get; set; }
        public string FYONGGONGTYPE { get; set; }
        public string FNATION { get; set; }
        public string FIMAGE { get; set; }
        public byte[] F_HXN_IMAGE { get; set; }
        public string FFAXIN { get; set; }
        public string FWORKCITY { get; set; }
        public string FCITY { get; set; }
        public int FGANGWEI { get; set; }
        public string FZHIJI { get; set; }
        public string FYGSTATE { get; set; }
        public string FZHENGZHI { get; set; }
    }
}
