//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.HXN_HR_ORG_GroupMetaData))]
    public partial class HXN_HR_ORG_Group
    {
        public int FID { get; set; }
        public string FNUMBER { get; set; }
        public string FGROUPID { get; set; }
        public long FPARENTID { get; set; }
        public string FFULLPARENTID { get; set; }
        public int FLEFT { get; set; }
        public int FRIGHT { get; set; }
    }
}
