//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.OpenPlatformSubscriberMetaData))]
    public partial class OpenPlatformSubscriber
    {
        public long Corp { get; set; }
        public string Openid { get; set; }
        public string PlatformType { get; set; }
        public string Nickname { get; set; }
        public string Headimgurl { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Gender { get; set; }
        public string TelePhone { get; set; }
        public string MobilePhone { get; set; }
        public int Integrate { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public System.DateTime EnrollTime { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
    }
}
