//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.OpenPlatformUserInfoMetaData))]
    public partial class OpenPlatformUserInfo
    {
        public byte Subscribe { get; set; }
        public string PlatformType { get; set; }
        public string Openid { get; set; }
        public string Nickname { get; set; }
        public byte Sex { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Headimgurl { get; set; }
        public string Privilege { get; set; }
        public Nullable<System.DateTime> SubscribeTime { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
