//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.SysCorpMetaData))]
    public partial class SysCorp
    {
        public long ID { get; set; }
        public long Parent { get; set; }
        public byte Priority { get; set; }
        public string Name { get; set; }
        public string BriefName { get; set; }
        public string Certificate { get; set; }
        public string CertificateNumber { get; set; }
        public string Ceo { get; set; }
        public string Postcode { get; set; }
        public string Faxcode { get; set; }
        public string Linkman { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Qq { get; set; }
        public string Wechat { get; set; }
        public string Weibo { get; set; }
        public long VirtualIntegral { get; set; }
        public long RealIntegral { get; set; }
        public long FeeType { get; set; }
        public decimal PrepayValve { get; set; }
        public decimal Balance { get; set; }
        public decimal FrozenBalance { get; set; }
        public decimal IncomingBalance { get; set; }
        public decimal Commission { get; set; }
        public decimal Discount { get; set; }
        public string Province { get; set; }
        public string Area { get; set; }
        public string County { get; set; }
        public string Community { get; set; }
        public string Address { get; set; }
        public long Status { get; set; }
        public long Type { get; set; }
        public long Grade { get; set; }
        public long Vocation { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public long Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<long> Auditor { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<long> Canceler { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string LogoUrl { get; set; }
        public string LogoIcon { get; set; }
    }
}
